[package]
name = "accountcat-ctl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
accountcat = { path = "../accountcat-server" }
tonic = "0.13.1"
